server:
  port: 9091
  servlet:
    context-path: /

springdoc:
  packagesToScan: by.darozhka.neighbour.controller
  swagger-ui:
    docExpansion: none
    path: /swagger-ui.html
    tagsSorter: alpha
    operationsSorter: alpha

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db-migrations/changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/neighbour
    username: neighbour
    password: neighbour
    hikari:
      maximum-pool-size: 10

logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE